python3 train.py --fold 0 --model linear_model_LogReg
python3 train.py --fold 1 --model linear_model_LogReg
python3 train.py --fold 2 --model linear_model_LogReg
python3 train.py --fold 3 --model linear_model_LogReg
python3 train.py --fold 4 --model linear_model_LogReg
python3 train.py --fold 0 --model linear_model_Lasso
python3 train.py --fold 1 --model linear_model_Lasso
python3 train.py --fold 2 --model linear_model_Lasso
python3 train.py --fold 3 --model linear_model_Lasso
python3 train.py --fold 4 --model linear_model_Lasso
python3 train.py --fold 0 --model rf
python3 train.py --fold 1 --model rf
python3 train.py --fold 2 --model rf
python3 train.py --fold 3 --model rf
python3 train.py --fold 4 --model rf
python3 train.py --fold 0 --model xgboost
python3 train.py --fold 1 --model xgboost
python3 train.py --fold 2 --model xgboost
python3 train.py --fold 3 --model xgboost
python3 train.py --fold 4 --model xgboost